Repository broadinstitute/gnomad_methods, pull requests merged in 2022-10, with the labels that each got.

#484 Add `coverage_mt` option to `annotate_sex` which takes an optional precomputed coverage MT to use for ploidy imputation instead of remaking it.
  gnomad/sample_qc/pipeline.py
Labels: Changelog: new feature

#492 Add function `get_chr_x_hom_alt_cutoffs`, add arguments to `infer_sex_karyotype` and `get_sex_expr` to use the new function and it's output.
  gnomad/sample_qc/pipeline.py
  gnomad/sample_qc/sex.py
Labels: Changelog: new feature

#493 Change to Black options to format long strings and add autopep8 to automatically wrap long comments
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  gnomad/assessment/summary_stats.py
  gnomad/assessment/validity_checks.py
  gnomad/resources/config.py
  gnomad/resources/grch37/gnomad_ld.py
  gnomad/resources/grch37/reference_data.py
  gnomad/resources/grch38/gnomad.py
  gnomad/resources/grch38/reference_data.py
  gnomad/resources/resource_utils.py
  gnomad/sample_qc/ancestry.py
  gnomad/sample_qc/pipeline.py
  gnomad/sample_qc/platform.py
  gnomad/sample_qc/relatedness.py
  gnomad/sample_qc/sex.py
  gnomad/utils/annotations.py
  gnomad/utils/constraint.py
  gnomad/utils/filtering.py
  gnomad/utils/gen_stats.py
  gnomad/utils/liftover.py
  gnomad/utils/plotting.py
  gnomad/utils/reference_genome.py
  gnomad/utils/sparse_mt.py
  gnomad/utils/vcf.py
  gnomad/utils/vep.py
  gnomad/variant_qc/evaluation.py
  gnomad/variant_qc/random_forest.py
  gnomad/variant_qc/training.py
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  tests/resources/test_resource_utils.py
Labels: Unplanned, Changelog: ignore

#489 Add additional_samples_to_drop option to `run_pca_with_relateds`
  gnomad/sample_qc/ancestry.py
Labels: Changelog: breaking change, Changelog: bug fix

#498 Change setup.py version to 0.6.3 for new release
  setup.py
Labels: Changelog: ignore
