Repository broadinstitute/gnomad_methods, pull requests merged in 2022-09, with the labels that each got.

#478 Add `gaussian_mixture_model_karyotype_assignment` function to assign sex karyotype using Gaussian mixture models
  gnomad/sample_qc/pipeline.py
  gnomad/sample_qc/sex.py
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature

#482 update the paths within import_args to use the gcp public bucket for grch38
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: ignore

#483 Update the paths within import_args to use the gcp public bucket for …
  gnomad/resources/grch37/reference_data.py
Labels: Unplanned, Changelog: ignore

#479 Add `variants_filter_lcr`, `variants_filter_segdup` and `variants_snv_only` options to `annotate_sex` to filter variants prior to variant only ploidy imputation
  gnomad/sample_qc/pipeline.py
Labels: Changelog: new feature

#480 Add an option `compute_x_frac_variants_hom_alt` to `annotate_sex` that computes the fraction of variants on chromosome X that are homozygous alternate per sample
  gnomad/sample_qc/pipeline.py
Labels: Changelog: new feature

#474 Add generic constraint functions - annotate_mutation_type(), trimer_from_heptamer(), collapse_strand(), add_most_severe_csq_to_tc_within_vep_root()
  gnomad/utils/constraint.py
  gnomad/utils/vep.py
Labels: Changelog: new feature

#486 Add more file types to `file_exists` for checking '_SUCCESS'
  gnomad/utils/file_utils.py
Labels: Unplanned, Changelog: new feature

#488 Fix to paths for VEP 101 resources in init script
  init_scripts/vep101-init.sh
Labels: Changelog: bug fix
