Repository broadinstitute/gnomad_methods, pull requests merged in 2023-08, with the labels that each got.

#569 Run `pip-compile --upgrade requirements-dev.in` and `pip-compile --upgrade docs/requirements.docs.in`
  docs/requirements.docs.txt
  requirements-dev.txt
Labels: Changelog: ignore

#572 Add function to merge histograms with the same bin_edges
  gnomad/utils/annotations.py
Labels: Changelog: new feature

#559 Speed up GKS annotations and add interval based annotation
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/annotations.py
Labels: ga4gh VRS

#565 Add option to also merge an array of counts/ints in the freq array merge
  gnomad/utils/annotations.py
Labels: v4, Frequency

#571 Update annotate_freq and qual_hists, add split_vds and compute_freq_by_strata
  gnomad/utils/annotations.py
  gnomad/utils/filtering.py
Labels: Changelog: new feature, Frequency

#573 A few small type changes in merge_freq_arrays and merge_histograms
  gnomad/utils/annotations.py
Labels: Changelog: ignore

#574 Fix callstats order in `merge_freq_arrays`
  gnomad/utils/annotations.py
Labels: Changelog: bug fix

#577 Modifications to `annotate_freq` to improve memory use
  gnomad/utils/annotations.py
Labels: Changelog: breaking change, Frequency

#576 Avoid DeprecationWarnings from superseded hail function and import [minor]
  gnomad/sample_qc/relatedness.py
  gnomad/utils/annotations.py
  gnomad/utils/file_utils.py
  gnomad/utils/filtering.py
  gnomad/utils/sparse_mt.py
  gnomad/variant_qc/random_forest.py
Labels: Changelog: bug fix

#578 Update python 3.8 -> 3.11
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  docs/requirements.docs.in
  docs/requirements.docs.txt
  gnomad/assessment/validity_checks.py
  gnomad/resources/resource_utils.py
  gnomad/sample_qc/filtering.py
  gnomad/sample_qc/pipeline.py
  gnomad/utils/gen_stats.py
  gnomad/utils/sparse_mt.py
  gnomad/utils/vep.py
  gnomad/variant_qc/evaluation.py
  pyproject.toml
  requirements-dev.in
  requirements-dev.txt
  tests/resources/test_resource_utils.py
Labels: dependencies

#579 Run count merge through dict of lists rather than single list
  gnomad/utils/annotations.py
Labels: Changelog: ignore, Frequency

#580 function to update sample annotations
  gnomad/utils/annotations.py
Labels: v4, annotation

#581 Fix circular import of `annotate_adj`
  gnomad/utils/filtering.py
Labels: Changelog: ignore

#583 Split vds change from list to dict
  gnomad/utils/annotations.py
  gnomad/utils/filtering.py
Labels: Changelog: ignore, Frequency

#584 Make naive_coalesce optional in `default_compute_info`
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, Variant QC annotation

#582 function to remove items from freq and freq_meta
  gnomad/utils/filtering.py
Labels: Changelog: new feature, annotation

#587 Fix `merge_freq_arrays` for cases with more than two arrays
  gnomad/utils/annotations.py
Labels: Changelog: bug fix
