Repository broadinstitute/gnomad_methods, pull requests merged in 2023-09, with the labels that each got.

#589 Fix `annotate_downsamplings` when used with a Table instead of a MatrixTable
  gnomad/utils/annotations.py
Labels: Changelog: ignore

#585 Add optional filter to freq meta sample counts
  gnomad/utils/filtering.py
Labels: Changelog: ignore, v4, Frequency

#593 When merging freq arrays, AF will be missing when AN is 0
  gnomad/utils/annotations.py
Labels: Changelog: ignore, Frequency

#592 Modify `apply_rf_model` to use `vector_to_array` from `pyspark.ml.functions` instead of `udf`
  gnomad/variant_qc/random_forest.py
Labels: Changelog: bug fix, Variant QC

#595 Add a `select_fields` option to `compute_freq_by_strata`
  gnomad/utils/annotations.py
Labels: Changelog: new feature, Frequency

#599 Add back write to parquet file in `apply_rf_model` and make `label` parameter optional
  gnomad/variant_qc/random_forest.py
Labels: Changelog: ignore, Variant QC

#597 Copy: Refactor variant report code and remove old functions
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/annotations.py
Labels: Changelog: new feature

#588 Update v4 exome coverage versions
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/sparse_mt.py
Labels: Changelog: ignore, Coverage

#605 Updates to allow for grouping and filtering by MANE transcripts
  gnomad/utils/constraint.py
  gnomad/utils/vep.py
Labels: Changelog: new feature, Constraint

#596 Copy of: Add gnomad_gks() and get_gks() for extracting gks information for a specified variant
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/annotations.py
  requirements.txt
Labels: Changelog: new feature, ga4gh VRS
