Repository broadinstitute/gnomad_methods, pull requests merged in 2023-06, with the labels that each got.

#550 v4 definitely has NFE
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: ignore

#545 Allow any frequency groupings
  gnomad/utils/annotations.py
Labels: Changelog: ignore, Frequency

#547 Add callstats option to inbreeding coeff
  gnomad/utils/annotations.py
Labels: Changelog: ignore, Frequency

#548 validity check code of VEP annotations in protein-coding genes
  gnomad/assessment/validity_checks.py
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: new feature, v4, annotation

#554 Add "remaining" to pops to remove for popmax for v4
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: ignore

#555 add optional ab_expr to qual_hists
  gnomad/utils/annotations.py
Labels: Changelog: ignore

#551 Merge freq array function and new frequency dictionary builder
  gnomad/utils/annotations.py
  gnomad/utils/release.py
Labels: Changelog: new feature, Frequency

#552 Add GRCh38 methylation sites resource
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: new feature

#546 add VEP 105 CSQ FIELDs
  gnomad/utils/vep.py
Labels: v4, annotation
