Repository broadinstitute/gnomad_methods, pull requests merged in 2023-12, with the labels that each got.

#647 Add RSEM summary function
  gnomad/utils/transcript_annotation.py
Labels: Changelog: new feature

#652 make vep_struct_to_csq compatible with vep 101
  gnomad/utils/vep.py
Labels: Changelog: ignore

#654 Suggestions to tx_annotate_mt PR
  gnomad/utils/transcript_annotation.py
Labels: Pext
