Repository broadinstitute/gnomad_methods, pull requests merged in 2023-10, with the labels that each got.

#614 Fix merge_histograms for NAs
  gnomad/utils/annotations.py
Labels: Changelog: ignore, Frequency

#609 Add aggregations to variant QC evaluation for additional plots
  gnomad/variant_qc/evaluation.py
  gnomad/variant_qc/pipeline.py
Labels: Changelog: new feature, Variant QC

#607 Changes made to get preliminary v4 vqsr results
  gnomad/variant_qc/vqsr.py
  gnomad/variant_qc/vqsr_resources.json
Labels: v4, Variant QC

#610 Add helpful parameters to `generate_freq_group_membership_array` and `compute_freq_by_strata`
  gnomad/utils/annotations.py
Labels: Changelog: ignore

#616 Add ability to retrieve max for any threshold in faf
  gnomad/utils/annotations.py
Labels: v4, Frequency

#608 add function to get max FAF from faf_expr
  gnomad/utils/annotations.py
Labels: Changelog: new feature

#618 Add option for ensembl only and upper_cov_cutoff for constraint functions
  gnomad/utils/constraint.py
  gnomad/utils/vep.py
Labels: Changelog: ignore

#615 Add optional stratification parameter to coverage
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, Coverage

#619 Fix v4 subset values
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: ignore

#622 Add methylation resource for chrX
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: new feature

#624 Add apply_keep_to_only_items_in_filter option to `filter_arrays_by_meta`
  gnomad/utils/filtering.py
Labels: Changelog: new feature

#626 Move ga4gh imports to their functions
  gnomad/utils/annotations.py
Labels: Changelog: bug fix

#628 Add gen_anc to SORT_ORDER
  gnomad/utils/vcf.py
Labels: Changelog: ignore

#630 Add pprint globals and a global/row length comparison, updates monoallelic expr in validity checks
  gnomad/assessment/validity_checks.py
Labels: Changelog: new feature

#631 update HGDP pops
  gnomad/resources/grch38/gnomad.py
Labels: v4

#634 Add Mane select filtering option to `get_summary_counts`
  gnomad/assessment/summary_stats.py
  gnomad/utils/vep.py
Labels: Changelog: new feature

#635 Add optional parameters to `set_female_y_metrics_to_na_expr` to use other frequency fields
  gnomad/utils/annotations.py
Labels: Changelog: new feature

#637 Update constraint.py
  gnomad/utils/constraint.py
Labels: Changelog: ignore

#636 Add option in build_models to skip coverage models
  gnomad/utils/constraint.py
Labels: Changelog: ignore

#640 v4 VCF export updates
  gnomad/utils/vcf.py
Labels: Changelog: ignore, v4

#641 VRS_States header number from R to .
  gnomad/utils/vcf.py
Labels: Changelog: ignore, v4

#642 Update resource paths
  docs/requirements.docs.txt
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/file_utils.py
  requirements-dev.txt
Labels: Changelog: new feature

#643 Drop async file exists function
  gnomad/utils/file_utils.py
Labels: Changelog: bug fix
