Repository broadinstitute/gnomad_methods, pull requests merged in 2024-09, with the labels that each got.

#729 Add `get_tissues_to_exclude` function to determine what tissues to exclude from transcript annotation calculations
  gnomad/utils/transcript_annotation.py
  tests/utils/test_transcript_annotation.py
Labels: Changelog: breaking change, Changelog: new feature, Pext

#731 Add retain cdf option for median calculations when computing info fields
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature

#732 Add `max_grpmax` option to `get_summary_stats_variant_filter_expr` for filtering by grpmax
  gnomad/assessment/summary_stats.py
Labels: Changelog: new feature, Release Stats
