Repository broadinstitute/gnomad_methods, pull requests merged in 2024-12, with the labels that each got.

#734 Add `get_mu_annotation_expr` function that prevents a shuffle from happening when annotating a HT with mutation rate and use in `annotate_with_mu`
  gnomad/utils/constraint.py
Labels: Changelog: new feature, Constraint

#741 Add support for filtering Hail Tables to `filter_to_trios`
  gnomad/sample_qc/relatedness.py
Labels: Changelog: new feature

#743 Add pext and constraint resources
  gnomad/resources/grch37/gnomad.py
  gnomad/resources/grch38/gnomad.py
Labels: Resources

#745 Generalize the `freq_bin_expr` function to take in a list of allele count and allele frequency cutoffs
  gnomad/assessment/summary_stats.py
Labels: Changelog: new feature

#746 Add function `parse_variant` to create a Struct with the locus and alleles from a variant string or contig, position, ref, and alt.
  gnomad/utils/parse.py
  tests/utils/test_parse.py
Labels: Changelog: new feature

#748 Modify `filter_vep_transcript_csqs_expr` so it can also accept hl.expr.StructExpression
  gnomad/utils/vep.py
Labels: Changelog: new feature

#747 Filter to Gencode CDS by genes and by exon paddings
  gnomad/utils/filtering.py
  init_scripts/vep81-init.sh
  init_scripts/vep85-init.sh
Labels: Changelog: new feature
