Repository broadinstitute/gnomad_methods, pull requests merged in 2024-01, with the labels that each got.

#655 Suggestions to tx_annotate_mt
  gnomad/utils/transcript_annotation.py
  gnomad/utils/vep.py
Labels: Pext

#649 Function to get expression proportion
  gnomad/utils/transcript_annotation.py
Labels: Changelog: new feature, Pext

#646 Add GTEx import resources
  gnomad/resources/grch37/reference_data.py
Labels: Changelog: new feature, Pext

#657 amr dict value description fix
  gnomad/sample_qc/ancestry.py
Labels: Changelog: ignore, Sample QC

#659 Add function `agg_by_strata`, which is a generalized version of the `compute_freq_by_strata`
  gnomad/utils/annotations.py
Labels: Changelog: new feature, Frequency, v4.1

#660 Clean up `compute_coverage_stats`, change it to use `agg_by_strata` and have an optional `group_membership_ht` parameter
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, Coverage, v4.1

#661 Add `densify_all_reference_sites` to perform a densify at all sites in a reference HT
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, Coverage, v4.1

#662 Add `compute_stats_per_ref_site` to generalize computation of aggregate stats at all sites in a reference Table
  gnomad/utils/annotations.py
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, v4.1

#651 Functions to process, filter, annotate and aggregate variants by transcript expression (get the pext scores per variant)
  gnomad/resources/grch37/reference_data.py
  gnomad/resources/grch38/reference_data.py
  gnomad/resources/resource_utils.py
  gnomad/utils/filtering.py
  gnomad/utils/transcript_annotation.py
  gnomad/utils/vep.py
Labels: Changelog: new feature, Pext

#669 Add gnomAD all sites allele number resource
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: new feature, Coverage

#668 Account for missingness in int64 to int32 VCF type conversion
  gnomad/utils/vcf.py
Labels: Changelog: bug fix

#658 Add mid to FAF and grpmax calcs
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/vcf.py
Labels: Changelog: breaking change, Frequency

#672 Add `read_args` parameter to the read functions of Resource Classes
  gnomad/resources/resource_utils.py
Labels: Changelog: new feature, Resources
