Repository broadinstitute/gnomad_methods, pull requests merged in 2024-04, with the labels that each got.

#633 Change `get_downsampling_freq_indices` and `downsampling_counts_expr` to support both 'pop' and 'gen_anc' keys in metadata
  gnomad/utils/constraint.py
Labels: Changelog: new feature

#690 Update POPS constant to contain a dictionary of both exomes and genomes
  gnomad/assessment/validity_checks.py
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/constraint.py
  gnomad/utils/release.py
Labels: Changelog: breaking change

#693 Fix `generic_field_check` in validity_checks.py print of failed checks
  gnomad/assessment/validity_checks.py
Labels: Changelog: bug fix

#691 remove hardcoding of v4 in gnomad_gks
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: ignore

#682 Add v4.1 to release globals
  gnomad/resources/grch38/gnomad.py
Labels: Changelog: ignore, v4.1, Resources

#696 Add joint filters info dict
  gnomad/utils/vcf.py
Labels: Changelog: ignore, VCF

#694 Add explode_downsamplings function
  gnomad/utils/constraint.py
Labels: Changelog: new feature

#697 Fix bug in joint filter dict
  gnomad/utils/vcf.py
Labels: Changelog: ignore
