Repository broadinstitute/gnomad_methods, pull requests merged in 2024-03, with the labels that each got.

#681 Add function for adding gencode annotation
  gnomad/utils/constraint.py
Labels: Changelog: new feature

#679 Small docstring edits for mane_select
  gnomad/utils/constraint.py
Labels: Changelog: ignore

#684 Replace 'ancestry' with genetic ancestry group for callstats in VCF header
  gnomad/utils/vcf.py
Labels: Changelog: ignore, VCF
