Repository broadinstitute/gnomad_methods, pull requests merged in 2024-07, with the labels that each got.

#713 Add `filter_vep_transcript_csqs_expr`, a version of `filter_vep_transcript_csqs` that takes and returns an ArrayExpression
  gnomad/utils/vep.py
Labels: Changelog: new feature

#716 Add create_vds function that only supports creating from gvcfs
  gnomad/utils/file_utils.py
Labels: Changelog: new feature, v5

#718 Add functions `fill_missing_key_combinations` and `missing_struct_expr`
  .pre-commit-config.yaml
  gnomad/utils/annotations.py
  tests/conftest.py
  tests/utils/test_annotations.py
Labels: Changelog: new feature

#717 Dependabot assigns PRs automatically and only creates them for security updates
  .github/dependabot.yml
Labels: Changelog: ignore
