Repository broadinstitute/gnomad_methods, pull requests merged in 2024-02, with the labels that each got.

#673 Add `get_is_haploid_expr`, `get_dp_gq_adj_expr`, `get_adj_het_ab_expr`, and some helpful parameters to `agg_by_strata` and `compute_stats_per_ref_site`
  gnomad/sample_qc/sex.py
  gnomad/utils/annotations.py
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature

#677 Add `sex_karyotype_field` as an argument to `compute_stats_per_ref_site` to include sex ploidy adjustment after densify
  gnomad/utils/sparse_mt.py
Labels: Changelog: new feature, Coverage

#617 Minor GKS formatting changes and addition of gnomAD flags to annotation
  gnomad/resources/grch38/gnomad.py
  gnomad/sample_qc/ancestry.py
  gnomad/utils/annotations.py
Labels: ga4gh VRS

#680 Change null to missing in `adjusted_sex_ploidy_expr`
  gnomad/sample_qc/sex.py
Labels: Changelog: ignore
