Repository broadinstitute/gnomad_methods, pull requests merged in 2024-08, with the labels that each got.

#721 pext runtime changes
  docs/_static/theme_overrides.css
  gnomad/utils/transcript_annotation.py
  tests/utils/test_annotations.py
  tests/utils/test_transcript_annotation.py
Labels: Changelog: ignore, Pext

#726 Update default vep version for context table resource
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: breaking change

#719 Add vds list option to create vds
  gnomad/utils/file_utils.py
Labels: Changelog: ignore, v5

#724 Add coverage_metric param to allow for different metrics of coverage and cov_model_type option to allow for linear or logarithmic
  gnomad/resources/grch38/gnomad.py
  gnomad/utils/constraint.py
Labels: Changelog: breaking change, Changelog: new feature

#727 Fix `tx_filter_variants_by_csqs` to correctly handle the `ignore_splicing` parameter
  .github/workflows/ci.yml
  gnomad/utils/transcript_annotation.py
  tests/resources/test_resource_utils.py
  tests/utils/test_transcript_annotation.py
Labels: Changelog: bug fix
