Repository broadinstitute/gnomad_methods, pull requests merged in 2025-05, with the labels that each got.

#778 Assign ONNX to 1.17.0 to avoid ImportError
  requirements.txt
Labels: dependencies

#776 remove index requirement from unfurl function
  gnomad/assessment/validity_checks.py
  tests/assessment/test_validity_checks.py
Labels: Changelog: breaking change

#781 Add May 2025 clinvar resource
  gnomad/resources/grch38/reference_data.py
Labels: Changelog: new feature, Resources
