Repository broadinstitute/gnomad_methods, pull requests merged in 2025-07, with the labels that each got.

#787 Update genetic ancestry terms
  gnomad/assessment/summary_stats.py
  gnomad/assessment/validity_checks.py
  gnomad/resources/grch37/gnomad.py
  gnomad/resources/grch38/gnomad.py
  gnomad/sample_qc/ancestry.py
  gnomad/utils/annotations.py
  gnomad/utils/constraint.py
  gnomad/utils/filtering.py
  gnomad/utils/plotting.py
  gnomad/utils/release.py
  gnomad/utils/vcf.py
  gnomad/variant_qc/ld.py
  tests/assessment/test_validity_checks.py
Labels: Changelog: breaking change

#790 Add coverage entry agg function
  gnomad/utils/sparse_mt.py
  tests/utils/test_sparse_mt.py
Labels: Changelog: new feature

#792 Remove Azure resources from `gnomad/resources/config.py`, `gnomad/resources/resource_utils.py`, `tests/resources/test_resource_utils.py`, and `docs/resource_sources.rst`
  docs/resource_sources.rst
  gnomad/resources/config.py
  gnomad/resources/resource_utils.py
  tests/resources/test_resource_utils.py
Labels: Changelog: breaking change

#794 Add LEN to compute_stats_per_ref_site after hail updates
  gnomad/utils/sparse_mt.py
Labels: Changelog: ignore
