Repository broadinstitute/gnomad_methods, pull requests merged in 2025-02, with the labels that each got.

#757 Add compute_and_check_summations function
  gnomad/assessment/validity_checks.py
  tests/assessment/test_validity_checks.py
Labels: Changelog: new feature

#760 Adapt `hl.de_novo` function
  gnomad/sample_qc/relatedness.py
  gnomad/utils/annotations.py
  tests/sample_qc/test_de_novo.py
  tests/utils/test_annotations.py
Labels: Changelog: new feature

#762 Add nhomalt_metric param and tests for check_raw_and_adj_callstats
  gnomad/assessment/validity_checks.py
  tests/assessment/test_validity_checks.py
Labels: Changelog: ignore

#764 Remove old hail init scripts
  init_scripts/gnomad-init.sh
  init_scripts/master-init.sh
Labels: Changelog: breaking change
